# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Skolt Sami spellchecker"
sms = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Skolt Sami, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
sms = "TRANSLATE: A spellchecker for Skolt Sami, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.sms"

[windows]
system_product_code = "{0B883A20-5944-4F44-91A6-E4C9953C1489}_is1"
legacy_product_codes = [
    { value = "1AC7B700-ADFD-4D66-B6F6-65434915FB4D", kind = "nsis" },
    { value = "2F8747C4-84A2-47F7-8AF1-0890564405E8", kind = "nsis" }
]
extra_locales = { sms-FI = "sms" }
[package.speller]
name = "Skolt Sami"
version = "1.0.2"

[package.grammar]
name = "Skolt Sami"
version = "0.1.0"

[package.tts-textproc]
name = "Skolt Sami"
version = "0.1.0"

[package.hyphenator]
name = "Skolt Sami"
version = "0.1.0"
