template = "https://github.com/giellalt/template-lang-und"
rev_id = 257
template_sha = "0b3fb3d8836831dedcfe3f4b9fcdc3e2aef12fa5"

[replacements]
__GLOTTOLOG_ID__ = "skol1241"
__REPO__ = "lang-sms"
__UND2C__ = "sms"
__UNDEFINED__ = "Skolt Sami"
__UND__ = "sms"
